### ISSUE TITLE
Link na barra de navegação não linka.

### ISSUE THREAD

**Issue by nathalia-nobrega** [nathalia-nobrega/Hyades-Web#1]
Tem uma tag <a> no código (index.html, linha 51) que não tá linkando pra seção que deveria. Ela deveria ir pra #quem_somos_section (index.html, linha 421), mas não vai.

**Comment by Wakerwind** [comment]
te vira aí

**Comment by Wakerwind** [comment]
Oi amiga, tudo bom?****

**Comment by nathalia-nobrega** [comment]
Oi amigo, o link na barra tá linkando já? Se não deixa pra fazer amanhã na
aula de pw

Em qua., 6 de mar. de 2024 20:16, Wakerwind ***@***.***>
escreveu:
